import { useEffect, useRef, useState } from "react";
import { Crown, Gem, Shield, Coins, Star, Flame, Zap, CircleDollarSign, Sparkles, LockKeyhole, Volume2, VolumeX, Gauge, Info } from "lucide-react";
import type { CSSProperties } from "react";
type SymbolName = "crown" | "gem" | "shield" | "coins" | "star" | "flame" | "zap" | "coin" | "wild" | "scatter";
type SpinResult = { id:string; symbols:SymbolName[]; outcome:string; bet:number; payout:number; balance:number; mode:"spin"|"buyBonus"; bonusSpins?:number; awardedFreeSpins?:number; freeSpinsRemaining?:number; winningPositions?:number[]; wins?:{line:number;symbol:SymbolName;count:number;payout:number;positions:number[]}[] };
const symbolMeta:Record<SymbolName,{label:string;Icon:typeof Crown;className:string}> = {
 crown:{label:"Crown",Icon:Crown,className:"rf-symbol-crown"},gem:{label:"Royal Gem",Icon:Gem,className:"rf-symbol-gem"},shield:{label:"Shield",Icon:Shield,className:"rf-symbol-shield"},coins:{label:"Treasure",Icon:Coins,className:"rf-symbol-coins"},star:{label:"Star",Icon:Star,className:"rf-symbol-star"},flame:{label:"Flame",Icon:Flame,className:"rf-symbol-flame"},zap:{label:"Lightning",Icon:Zap,className:"rf-symbol-zap"},coin:{label:"Gold",Icon:CircleDollarSign,className:"rf-symbol-coin"},wild:{label:"WILD",Icon:Sparkles,className:"rf-symbol-wild"},scatter:{label:"SCATTER",Icon:Star,className:"rf-symbol-scatter"}
};
const paytable=[["CROWN","3: 60× · 4: 300× · 5: 3,250×"],["GEM","3: 45× · 4: 225× · 5: 2,450×"],["SHIELD","3: 35× · 4: 175× · 5: 1,900×"],["TREASURE","3: 25× · 4: 125× · 5: 1,400×"],["STAR","3: 20× · 4: 100× · 5: 1,100×"],["FLAME","3: 15× · 4: 75× · 5: 850×"],["LIGHTNING","3: 10× · 4: 50× · 5: 600×"],["GOLD","3: 5× · 4: 25× · 5: 350×"],["WILD","Substitutes for regular symbols"],["SCATTER","3 or more trigger Free Spins"]];
function requestId(){return typeof crypto.randomUUID==="function"?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,"0")).join("");}
function playTone(kind:"spin"|"stop"|"win"|"bonus"){try{const AudioCtx=window.AudioContext||(window as any).webkitAudioContext;const ctx=new AudioCtx();const notes=kind==="win"?[523,659,784,1047]:kind==="bonus"?[392,523,659,784,988]:kind==="stop"?[220]:[150,190,240];notes.forEach((freq,i)=>{const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type=kind==="spin"?"sawtooth":"sine";osc.frequency.value=freq;gain.gain.setValueAtTime(.0001,ctx.currentTime+i*.07);gain.gain.exponentialRampToValueAtTime(kind==="spin"?.018:.07,ctx.currentTime+i*.07+.015);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+i*.07+.15);osc.connect(gain);gain.connect(ctx.destination);osc.start(ctx.currentTime+i*.07);osc.stop(ctx.currentTime+i*.07+.17);});window.setTimeout(()=>void ctx.close(),1000);}catch{/* Audio is optional. */}}
export default function RoyalFortune(){
 const [balance,setBalance]=useState<number|null>(null),[bet,setBet]=useState(10),[result,setResult]=useState<SpinResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("Choose your stake, set a speed and spin."),[mode,setMode]=useState<"demo"|"real">("demo"),[soundOn,setSoundOn]=useState(false),[speed,setSpeed]=useState<"slow"|"normal"|"turbo">("normal"),[freeSpins,setFreeSpins]=useState(0),[reelStops,setReelStops]=useState(0);
 const timers=useRef<number[]>([]);
 useEffect(()=>{let live=true;fetch("/api/games/royal-fortune",{credentials:"same-origin",cache:"no-store"}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Could not load game.");if(live){setBalance(Number(d.balance));setFreeSpins(Number(d.freeSpins||0));}}).catch(e=>{if(live)setError(e instanceof Error?e.message:"Could not load demo balance.");});return()=>{live=false;timers.current.forEach(clearTimeout);};},[]);
 const play=async(action:"spin"|"buyBonus")=>{if(busy||balance===null)return;if(action==="buyBonus"&&balance<bet*100){setError("Not enough demo credits for Buy Bonus.");return;}if(action==="spin"&&freeSpins<=0&&balance<bet){setError("Not enough demo credits. Lower your bet.");return;}setBusy(true);setError("");setReelStops(0);setMessage(action==="buyBonus"?"Entering the Royal Bonus feature…":freeSpins>0?"Free Spin in progress…":"Reels spinning…");if(soundOn)playTone("spin");const base=speed==="slow"?850:speed==="normal"?520:240;timers.current.forEach(clearTimeout);timers.current=[];for(let i=0;i<5;i++)timers.current.push(window.setTimeout(()=>{setReelStops(v=>v+1);if(soundOn)playTone("stop");},base*(i+1)));try{const response=await fetch("/api/games/royal-fortune",{method:"POST",credentials:"same-origin",cache:"no-store",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,bet,requestId:requestId()})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Spin failed. Your demo balance has not been changed.");await new Promise(resolve=>window.setTimeout(resolve,base*5+180));setResult(data.result);setBalance(Number(data.balance));setFreeSpins(Number(data.freeSpins??data.result.freeSpinsRemaining??(freeSpins>0?freeSpins-1:0)));if(data.result.payout>0&&soundOn)playTone(data.result.awardedFreeSpins?"bonus":"win");setMessage(data.result.awardedFreeSpins?"SCATTER BONUS · "+data.result.awardedFreeSpins+" FREE SPINS AWARDED":action==="buyBonus"?"BONUS COMPLETE · "+Number(data.result.payout).toLocaleString()+" demo credits returned across "+(data.result.bonusSpins||10)+" rounds":data.result.payout>0?"WIN · "+Number(data.result.payout).toLocaleString()+" demo credits":Number(data.freeSpins||0)>0?"FREE SPINS · "+data.freeSpins+" remaining":"No win this spin. Try another combination.");}catch(e){setError(e instanceof Error?e.message:"Could not complete the spin.");}finally{timers.current.forEach(clearTimeout);setBusy(false);}};
 const symbols:SymbolName[]=result?.symbols?.length===20?result.symbols:["crown","gem","wild","shield","coins","star","flame","scatter","zap","coin","gem","crown","coins","shield","star","coin","flame","gem","zap","crown"];
 const winning=new Set(result?.winningPositions||[]);
 return <div className="rf-game">
 <div className="rf-game-top"><div className="rf-title-lockup"><div className="rf-emblem"><Crown size={28}/><span>✦</span></div><div><span className="rf-eyebrow">MAXWIN ORIGINAL · SLOT 001</span><h3>ROYAL <em>FORTUNE</em></h3><p>Fortune favours the bold.</p></div></div><div className="rf-top-actions"><span className="rf-status"><span/> DEMO PLAY</span><button className="rf-icon-button" type="button" onClick={()=>setSoundOn(v=>!v)} aria-label={soundOn?"Turn sound off":"Turn sound on"}>{soundOn?<Volume2 size={16}/>:<VolumeX size={16}/>}<small>{soundOn?"SOUND ON":"SOUND OFF"}</small></button></div></div>
 <div className="rf-mode-tabs"><button className={mode==="demo"?"active":""} onClick={()=>setMode("demo")}>DEMO PLAY <small>FREE CREDITS</small></button><button className={mode==="real"?"active rf-real-tab":"rf-real-tab"} onClick={()=>setMode("real")}>REAL MONEY <small><LockKeyhole size={11}/> LOCKED</small></button></div>
 {mode==="real"&&<div className="rf-locked-notice"><LockKeyhole size={18}/><span><b>Real-money play is not enabled.</b><small>No deposits or cash wagers are accepted. Licensing, age/jurisdiction controls, audited RNG, wallet settlement and withdrawals must be independently verified first.</small></span></div>}
 <div className="rf-cabinet"><div className="rf-cabinet-header"><span><Sparkles size={14}/> ROYAL REELS</span><span>5 REELS <i/> 4 ROWS <i/> WILD + SCATTER</span></div><div className={"rf-reel-window rf-speed-"+speed+(busy?" is-spinning":"")} aria-label="Five reels with four symbols each">{symbols.map((name,i)=>{const item=symbolMeta[name]||symbolMeta.crown;const Icon=item.Icon;const reel=Math.floor(i/4);return <div className={"rf-reel "+item.className+(winning.has(i)?" rf-reel-win":"")+(busy&&reelStops<=reel?" rf-reel-spinning":"")} style={{"--reel-delay":(reel*.11)+"s"} as CSSProperties} key={(result?.id||"initial")+i}><span className="rf-reel-glow"/><Icon size={35} strokeWidth={1.8}/><small>{item.label}</small></div>;})}</div><div className="rf-machine-footer"><span>20 SYMBOL POSITIONS</span><span>SCATTER → FREE SPINS</span><span>WILD SUBSTITUTES</span></div></div>
 <div className="rf-speed-panel"><span><Gauge size={16}/> SPIN SPEED</span><div>{(["slow","normal","turbo"] as const).map(s=><button key={s} disabled={busy} className={speed===s?"active":""} onClick={()=>setSpeed(s)}>{s==="slow"?"SLOW":s==="normal"?"NORMAL":"TURBO"}</button>)}</div></div>
 {freeSpins>0&&<div className="rf-free-spin-banner"><Sparkles size={19}/><span><b>{freeSpins} FREE SPINS REMAINING</b><small>Free spins do not deduct your demo balance.</small></span></div>}
 <div className="rf-balance-row"><div className="rf-credit-panel"><span>DEMO CREDIT BALANCE</span><strong>{balance===null?"—":balance.toLocaleString()}</strong><small>Credits have no cash value</small></div><div className="rf-bet-control"><label htmlFor="rf-bet">TOTAL BET / SPIN</label><div><button disabled={busy} onClick={()=>setBet(v=>Math.max(10,v-10))} aria-label="Lower bet">−</button><strong>{bet.toLocaleString()}</strong><button disabled={busy} onClick={()=>setBet(v=>Math.min(100,v+10))} aria-label="Raise bet">+</button></div><small>10 paylines · {bet/10} credit per line</small></div></div>
 <div className="rf-action-row"><button className="rf-spin-button" disabled={busy||balance===null||(balance<bet&&freeSpins===0)||mode==="real"} onClick={()=>void play("spin")}>{busy?<><span className="rf-spinner"/> SPINNING…</>:<><span>✦</span> SPIN <small>{freeSpins>0?"FREE":bet+" CREDITS"}</small></>}</button><button className="rf-buy-button" disabled={busy||balance===null||balance<bet*100||mode==="real"} onClick={()=>void play("buyBonus")}><Crown size={18}/><span>BUY BONUS<small>100× BET · {(bet*100).toLocaleString()}</small></span></button></div>
 {error&&<p className="rf-error" role="alert">{error}</p>}<p className={"rf-message "+(result?.payout?"is-win":"")} aria-live="polite">{message}</p>{result&&<div className="rf-last-result"><span>LAST RESULT <small>{result.mode==="buyBonus"?"BUY BONUS · "+(result.bonusSpins||10)+" ROUNDS":"BASE GAME"}</small></span><strong>+{result.payout.toLocaleString()} <small>DEMO CREDITS</small></strong></div>}
 <div className="rf-info-grid"><div><span>THEORETICAL RTP</span><b>~96%*</b></div><div><span>PAYLINES</span><b>10</b></div><div><span>BONUS BUY</span><b>100× BET</b></div></div><details className="rf-paytable"><summary><Info size={14}/> PAYTABLE & GAME RULES</summary><div>{paytable.map(([name,values])=><div key={name}><span>{name}</span><b>{values}</b></div>)}</div><p>*Demo game math only. RTP is not independently certified and is not a guarantee of any session outcome. No real-money wagers are accepted.</p></details><div className="rf-demo-disclaimer">DEMO ONLY · No deposits, transfers or cash withdrawals. Real-money play remains locked.</div>
 </div>;
}
